vhr:
  host: 127.0.0.1
  mysql:
    password: 111
  redis:
    password: 111


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${vhr.mysql.password}
    url: jdbc:mysql://${vhr.host}:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: ${vhr.host}
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: ${vhr.host}
    database: 0
    port: 6379
    password: ${vhr.redis.password}
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://127.0.0.1/